### ISSUE TITLE
Repl not displaying properly

### ISSUE THREAD

**Issue by martinezjf2** [learn-co-curriculum/phase-0-pac-1-the-assignment-expression#4]
### Canvas Link

https://learning.flatironschool.com/courses/5729/pages/the-assignment-expression?module_item_id=395706

### Concern

Repl is not displaying the content or files for the students. It is displaying a 404 error that students can practice their code on based on the instructions.

### Additional Context

<img width="943" alt="Screen Shot 2022-06-23 at 2 30 11 PM" src="https://user-images.githubusercontent.com/57267088/175369703-b7d4708d-5085-4040-a566-c7a5e42d39a2.png">

**Comment by lizbur10** [comment]
Thanks @martinezjf2! This should now be fixed 💙
